export const ActionTypes = {
    SET_ALL_PRODUCTS: 'SET_ALL_PRODUCTS',
    REMOVE_SELECTED_PRODUCT:'REMOVE_SELECTED_PRODUCT',
    ADD_TO_CART:'ADD_TO_CART',
    QUANTITY_PRODUCT:'QUANTITY_PRODUCT',
    LOAD_CURRENT_ITEM:'LOAD_CURRENT_ITEM'
}